version: "3.8"

services:
    app:
        command: ["/gpt_bot/docker/app.sh"]
        build:
          context: .
          dockerfile: Dockerfile
        container_name: fastapi_app
        ports:
          - "9999:5005"
        env_file:
          - .env
        environment:
          - MONGODB_URL=mongodb://mongo_db
        depends_on:
          - db
        networks:
        - custom
    db:
        container_name: "mongo_db"
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - /var/lib/mongodb/:/data/db
        networks:
        - custom
networks:
  custom:
    driver: bridge